/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as BecomeAClipperRouteImport } from './routes/become-a-clipper'
import { Route as ForBrandsRouteImport } from './routes/for-brands'
import { Route as ForClippersRouteImport } from './routes/for-clippers'
import { Route as ForCreatorsRouteImport } from './routes/for-creators'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedBusinessRouteRouteImport } from './routes/_authenticated/business/route'
import { Route as AuthenticatedClipperRouteRouteImport } from './routes/_authenticated/clipper/route'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as SignupTypeRouteImport } from './routes/signup.$type'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'
import { Route as AuthenticatedAdminBansRouteImport } from './routes/_authenticated/admin/bans'
import { Route as AuthenticatedAdminClippersRouteImport } from './routes/_authenticated/admin/clippers'
import { Route as AuthenticatedAdminEmailRouteImport } from './routes/_authenticated/admin/email'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin/payments'
import { Route as AuthenticatedAdminPayoutsRouteImport } from './routes/_authenticated/admin/payouts'
import { Route as AuthenticatedAdminScraperRouteImport } from './routes/_authenticated/admin/scraper'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminViewsRouteImport } from './routes/_authenticated/admin/views'
import { Route as AuthenticatedBusinessIndexRouteImport } from './routes/_authenticated/business/index'
import { Route as AuthenticatedBusinessNewRouteImport } from './routes/_authenticated/business/new'
import { Route as AuthenticatedClipperIndexRouteImport } from './routes/_authenticated/clipper/index'
import { Route as AuthenticatedClipperClipsRouteImport } from './routes/_authenticated/clipper/clips'
import { Route as AuthenticatedClipperProfileRouteImport } from './routes/_authenticated/clipper/profile'
import { Route as AuthenticatedUniversityIndexRouteImport } from './routes/_authenticated/university/index'
import { Route as AuthenticatedUniversityCourseIdRouteImport } from './routes/_authenticated/university/$courseId'
import { Route as ApiPublicReclaimSlotsRouteImport } from './routes/api/public/reclaim-slots'
import { Route as AuthenticatedAdminUniversityIndexRouteImport } from './routes/_authenticated/admin/university/index'
import { Route as AuthenticatedAdminUniversityCourseIdRouteImport } from './routes/_authenticated/admin/university/$courseId'
import { Route as AuthenticatedBusinessAnalyticsIndexRouteImport } from './routes/_authenticated/business/analytics/index'
import { Route as AuthenticatedBusinessAnalyticsCampaignIdRouteImport } from './routes/_authenticated/business/analytics/$campaignId'
import { Route as AuthenticatedClipperCampaignCampaignIdRouteImport } from './routes/_authenticated/clipper/campaign.$campaignId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAClipperRoute = BecomeAClipperRouteImport.update({
  id: '/become-a-clipper',
  path: '/become-a-clipper',
  getParentRoute: () => rootRouteImport,
} as any)
const ForBrandsRoute = ForBrandsRouteImport.update({
  id: '/for-brands',
  path: '/for-brands',
  getParentRoute: () => rootRouteImport,
} as any)
const ForClippersRoute = ForClippersRouteImport.update({
  id: '/for-clippers',
  path: '/for-clippers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForCreatorsRoute = ForCreatorsRouteImport.update({
  id: '/for-creators',
  path: '/for-creators',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBusinessRouteRoute =
  AuthenticatedBusinessRouteRouteImport.update({
    id: '/business',
    path: '/business',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClipperRouteRoute =
  AuthenticatedClipperRouteRouteImport.update({
    id: '/clipper',
    path: '/clipper',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const SignupTypeRoute = SignupTypeRouteImport.update({
  id: '/signup/$type',
  path: '/signup/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBansRoute = AuthenticatedAdminBansRouteImport.update({
  id: '/bans',
  path: '/bans',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminClippersRoute =
  AuthenticatedAdminClippersRouteImport.update({
    id: '/clippers',
    path: '/clippers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEmailRoute = AuthenticatedAdminEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPayoutsRoute =
  AuthenticatedAdminPayoutsRouteImport.update({
    id: '/payouts',
    path: '/payouts',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminScraperRoute =
  AuthenticatedAdminScraperRouteImport.update({
    id: '/scraper',
    path: '/scraper',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminViewsRoute = AuthenticatedAdminViewsRouteImport.update({
  id: '/views',
  path: '/views',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedBusinessIndexRoute =
  AuthenticatedBusinessIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedBusinessRouteRoute,
  } as any)
const AuthenticatedBusinessNewRoute =
  AuthenticatedBusinessNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedBusinessRouteRoute,
  } as any)
const AuthenticatedClipperIndexRoute =
  AuthenticatedClipperIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClipperRouteRoute,
  } as any)
const AuthenticatedClipperClipsRoute =
  AuthenticatedClipperClipsRouteImport.update({
    id: '/clips',
    path: '/clips',
    getParentRoute: () => AuthenticatedClipperRouteRoute,
  } as any)
const AuthenticatedClipperProfileRoute =
  AuthenticatedClipperProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedClipperRouteRoute,
  } as any)
const AuthenticatedUniversityIndexRoute =
  AuthenticatedUniversityIndexRouteImport.update({
    id: '/university/',
    path: '/university/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUniversityCourseIdRoute =
  AuthenticatedUniversityCourseIdRouteImport.update({
    id: '/university/$courseId',
    path: '/university/$courseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicReclaimSlotsRoute = ApiPublicReclaimSlotsRouteImport.update({
  id: '/api/public/reclaim-slots',
  path: '/api/public/reclaim-slots',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminUniversityIndexRoute =
  AuthenticatedAdminUniversityIndexRouteImport.update({
    id: '/university/',
    path: '/university/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUniversityCourseIdRoute =
  AuthenticatedAdminUniversityCourseIdRouteImport.update({
    id: '/university/$courseId',
    path: '/university/$courseId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedBusinessAnalyticsIndexRoute =
  AuthenticatedBusinessAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => AuthenticatedBusinessRouteRoute,
  } as any)
const AuthenticatedBusinessAnalyticsCampaignIdRoute =
  AuthenticatedBusinessAnalyticsCampaignIdRouteImport.update({
    id: '/analytics/$campaignId',
    path: '/analytics/$campaignId',
    getParentRoute: () => AuthenticatedBusinessRouteRoute,
  } as any)
const AuthenticatedClipperCampaignCampaignIdRoute =
  AuthenticatedClipperCampaignCampaignIdRouteImport.update({
    id: '/campaign/$campaignId',
    path: '/campaign/$campaignId',
    getParentRoute: () => AuthenticatedClipperRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/become-a-clipper': typeof BecomeAClipperRoute
  '/for-brands': typeof ForBrandsRoute
  '/for-clippers': typeof ForClippersRoute
  '/for-creators': typeof ForCreatorsRoute
  '/login': typeof LoginRoute
  '/preview': typeof PreviewRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/business': typeof AuthenticatedBusinessRouteRouteWithChildren
  '/clipper': typeof AuthenticatedClipperRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/signup/$type': typeof SignupTypeRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/bans': typeof AuthenticatedAdminBansRoute
  '/admin/clippers': typeof AuthenticatedAdminClippersRoute
  '/admin/email': typeof AuthenticatedAdminEmailRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/admin/scraper': typeof AuthenticatedAdminScraperRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/views': typeof AuthenticatedAdminViewsRoute
  '/business/new': typeof AuthenticatedBusinessNewRoute
  '/clipper/clips': typeof AuthenticatedClipperClipsRoute
  '/clipper/profile': typeof AuthenticatedClipperProfileRoute
  '/university/$courseId': typeof AuthenticatedUniversityCourseIdRoute
  '/api/public/reclaim-slots': typeof ApiPublicReclaimSlotsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/business/': typeof AuthenticatedBusinessIndexRoute
  '/clipper/': typeof AuthenticatedClipperIndexRoute
  '/university/': typeof AuthenticatedUniversityIndexRoute
  '/admin/university/$courseId': typeof AuthenticatedAdminUniversityCourseIdRoute
  '/business/analytics/$campaignId': typeof AuthenticatedBusinessAnalyticsCampaignIdRoute
  '/clipper/campaign/$campaignId': typeof AuthenticatedClipperCampaignCampaignIdRoute
  '/admin/university/': typeof AuthenticatedAdminUniversityIndexRoute
  '/business/analytics/': typeof AuthenticatedBusinessAnalyticsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/become-a-clipper': typeof BecomeAClipperRoute
  '/for-brands': typeof ForBrandsRoute
  '/for-clippers': typeof ForClippersRoute
  '/for-creators': typeof ForCreatorsRoute
  '/login': typeof LoginRoute
  '/preview': typeof PreviewRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/signup/$type': typeof SignupTypeRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/bans': typeof AuthenticatedAdminBansRoute
  '/admin/clippers': typeof AuthenticatedAdminClippersRoute
  '/admin/email': typeof AuthenticatedAdminEmailRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/admin/scraper': typeof AuthenticatedAdminScraperRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/views': typeof AuthenticatedAdminViewsRoute
  '/business/new': typeof AuthenticatedBusinessNewRoute
  '/clipper/clips': typeof AuthenticatedClipperClipsRoute
  '/clipper/profile': typeof AuthenticatedClipperProfileRoute
  '/university/$courseId': typeof AuthenticatedUniversityCourseIdRoute
  '/api/public/reclaim-slots': typeof ApiPublicReclaimSlotsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/business': typeof AuthenticatedBusinessIndexRoute
  '/clipper': typeof AuthenticatedClipperIndexRoute
  '/university': typeof AuthenticatedUniversityIndexRoute
  '/admin/university/$courseId': typeof AuthenticatedAdminUniversityCourseIdRoute
  '/business/analytics/$campaignId': typeof AuthenticatedBusinessAnalyticsCampaignIdRoute
  '/clipper/campaign/$campaignId': typeof AuthenticatedClipperCampaignCampaignIdRoute
  '/admin/university': typeof AuthenticatedAdminUniversityIndexRoute
  '/business/analytics': typeof AuthenticatedBusinessAnalyticsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/become-a-clipper': typeof BecomeAClipperRoute
  '/for-brands': typeof ForBrandsRoute
  '/for-clippers': typeof ForClippersRoute
  '/for-creators': typeof ForCreatorsRoute
  '/login': typeof LoginRoute
  '/preview': typeof PreviewRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/business': typeof AuthenticatedBusinessRouteRouteWithChildren
  '/_authenticated/clipper': typeof AuthenticatedClipperRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/signup/$type': typeof SignupTypeRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/bans': typeof AuthenticatedAdminBansRoute
  '/_authenticated/admin/clippers': typeof AuthenticatedAdminClippersRoute
  '/_authenticated/admin/email': typeof AuthenticatedAdminEmailRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/payouts': typeof AuthenticatedAdminPayoutsRoute
  '/_authenticated/admin/scraper': typeof AuthenticatedAdminScraperRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/views': typeof AuthenticatedAdminViewsRoute
  '/_authenticated/business/new': typeof AuthenticatedBusinessNewRoute
  '/_authenticated/clipper/clips': typeof AuthenticatedClipperClipsRoute
  '/_authenticated/clipper/profile': typeof AuthenticatedClipperProfileRoute
  '/_authenticated/university/$courseId': typeof AuthenticatedUniversityCourseIdRoute
  '/api/public/reclaim-slots': typeof ApiPublicReclaimSlotsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/business/': typeof AuthenticatedBusinessIndexRoute
  '/_authenticated/clipper/': typeof AuthenticatedClipperIndexRoute
  '/_authenticated/university/': typeof AuthenticatedUniversityIndexRoute
  '/_authenticated/admin/university/$courseId': typeof AuthenticatedAdminUniversityCourseIdRoute
  '/_authenticated/business/analytics/$campaignId': typeof AuthenticatedBusinessAnalyticsCampaignIdRoute
  '/_authenticated/clipper/campaign/$campaignId': typeof AuthenticatedClipperCampaignCampaignIdRoute
  '/_authenticated/admin/university/': typeof AuthenticatedAdminUniversityIndexRoute
  '/_authenticated/business/analytics/': typeof AuthenticatedBusinessAnalyticsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/become-a-clipper'
    | '/for-brands'
    | '/for-clippers'
    | '/for-creators'
    | '/login'
    | '/preview'
    | '/admin'
    | '/business'
    | '/clipper'
    | '/dashboard'
    | '/notifications'
    | '/signup/$type'
    | '/admin/analytics'
    | '/admin/bans'
    | '/admin/clippers'
    | '/admin/email'
    | '/admin/payments'
    | '/admin/payouts'
    | '/admin/scraper'
    | '/admin/users'
    | '/admin/views'
    | '/business/new'
    | '/clipper/clips'
    | '/clipper/profile'
    | '/university/$courseId'
    | '/api/public/reclaim-slots'
    | '/admin/'
    | '/business/'
    | '/clipper/'
    | '/university/'
    | '/admin/university/$courseId'
    | '/business/analytics/$campaignId'
    | '/clipper/campaign/$campaignId'
    | '/admin/university/'
    | '/business/analytics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/become-a-clipper'
    | '/for-brands'
    | '/for-clippers'
    | '/for-creators'
    | '/login'
    | '/preview'
    | '/dashboard'
    | '/notifications'
    | '/signup/$type'
    | '/admin/analytics'
    | '/admin/bans'
    | '/admin/clippers'
    | '/admin/email'
    | '/admin/payments'
    | '/admin/payouts'
    | '/admin/scraper'
    | '/admin/users'
    | '/admin/views'
    | '/business/new'
    | '/clipper/clips'
    | '/clipper/profile'
    | '/university/$courseId'
    | '/api/public/reclaim-slots'
    | '/admin'
    | '/business'
    | '/clipper'
    | '/university'
    | '/admin/university/$courseId'
    | '/business/analytics/$campaignId'
    | '/clipper/campaign/$campaignId'
    | '/admin/university'
    | '/business/analytics'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/become-a-clipper'
    | '/for-brands'
    | '/for-clippers'
    | '/for-creators'
    | '/login'
    | '/preview'
    | '/_authenticated/admin'
    | '/_authenticated/business'
    | '/_authenticated/clipper'
    | '/_authenticated/dashboard'
    | '/_authenticated/notifications'
    | '/signup/$type'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/bans'
    | '/_authenticated/admin/clippers'
    | '/_authenticated/admin/email'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/payouts'
    | '/_authenticated/admin/scraper'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/views'
    | '/_authenticated/business/new'
    | '/_authenticated/clipper/clips'
    | '/_authenticated/clipper/profile'
    | '/_authenticated/university/$courseId'
    | '/api/public/reclaim-slots'
    | '/_authenticated/admin/'
    | '/_authenticated/business/'
    | '/_authenticated/clipper/'
    | '/_authenticated/university/'
    | '/_authenticated/admin/university/$courseId'
    | '/_authenticated/business/analytics/$campaignId'
    | '/_authenticated/clipper/campaign/$campaignId'
    | '/_authenticated/admin/university/'
    | '/_authenticated/business/analytics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  BecomeAClipperRoute: typeof BecomeAClipperRoute
  ForBrandsRoute: typeof ForBrandsRoute
  ForClippersRoute: typeof ForClippersRoute
  ForCreatorsRoute: typeof ForCreatorsRoute
  LoginRoute: typeof LoginRoute
  PreviewRoute: typeof PreviewRoute
  SignupTypeRoute: typeof SignupTypeRoute
  ApiPublicReclaimSlotsRoute: typeof ApiPublicReclaimSlotsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-clipper': {
      id: '/become-a-clipper'
      path: '/become-a-clipper'
      fullPath: '/become-a-clipper'
      preLoaderRoute: typeof BecomeAClipperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-brands': {
      id: '/for-brands'
      path: '/for-brands'
      fullPath: '/for-brands'
      preLoaderRoute: typeof ForBrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-clippers': {
      id: '/for-clippers'
      path: '/for-clippers'
      fullPath: '/for-clippers'
      preLoaderRoute: typeof ForClippersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-creators': {
      id: '/for-creators'
      path: '/for-creators'
      fullPath: '/for-creators'
      preLoaderRoute: typeof ForCreatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business': {
      id: '/_authenticated/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof AuthenticatedBusinessRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clipper': {
      id: '/_authenticated/clipper'
      path: '/clipper'
      fullPath: '/clipper'
      preLoaderRoute: typeof AuthenticatedClipperRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/signup/$type': {
      id: '/signup/$type'
      path: '/signup/$type'
      fullPath: '/signup/$type'
      preLoaderRoute: typeof SignupTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/bans': {
      id: '/_authenticated/admin/bans'
      path: '/bans'
      fullPath: '/admin/bans'
      preLoaderRoute: typeof AuthenticatedAdminBansRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/clippers': {
      id: '/_authenticated/admin/clippers'
      path: '/clippers'
      fullPath: '/admin/clippers'
      preLoaderRoute: typeof AuthenticatedAdminClippersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/email': {
      id: '/_authenticated/admin/email'
      path: '/email'
      fullPath: '/admin/email'
      preLoaderRoute: typeof AuthenticatedAdminEmailRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/payouts': {
      id: '/_authenticated/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AuthenticatedAdminPayoutsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/scraper': {
      id: '/_authenticated/admin/scraper'
      path: '/scraper'
      fullPath: '/admin/scraper'
      preLoaderRoute: typeof AuthenticatedAdminScraperRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/views': {
      id: '/_authenticated/admin/views'
      path: '/views'
      fullPath: '/admin/views'
      preLoaderRoute: typeof AuthenticatedAdminViewsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/business/': {
      id: '/_authenticated/business/'
      path: '/'
      fullPath: '/business/'
      preLoaderRoute: typeof AuthenticatedBusinessIndexRouteImport
      parentRoute: typeof AuthenticatedBusinessRouteRoute
    }
    '/_authenticated/business/new': {
      id: '/_authenticated/business/new'
      path: '/new'
      fullPath: '/business/new'
      preLoaderRoute: typeof AuthenticatedBusinessNewRouteImport
      parentRoute: typeof AuthenticatedBusinessRouteRoute
    }
    '/_authenticated/clipper/': {
      id: '/_authenticated/clipper/'
      path: '/'
      fullPath: '/clipper/'
      preLoaderRoute: typeof AuthenticatedClipperIndexRouteImport
      parentRoute: typeof AuthenticatedClipperRouteRoute
    }
    '/_authenticated/clipper/clips': {
      id: '/_authenticated/clipper/clips'
      path: '/clips'
      fullPath: '/clipper/clips'
      preLoaderRoute: typeof AuthenticatedClipperClipsRouteImport
      parentRoute: typeof AuthenticatedClipperRouteRoute
    }
    '/_authenticated/clipper/profile': {
      id: '/_authenticated/clipper/profile'
      path: '/profile'
      fullPath: '/clipper/profile'
      preLoaderRoute: typeof AuthenticatedClipperProfileRouteImport
      parentRoute: typeof AuthenticatedClipperRouteRoute
    }
    '/_authenticated/university/': {
      id: '/_authenticated/university/'
      path: '/university'
      fullPath: '/university/'
      preLoaderRoute: typeof AuthenticatedUniversityIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/university/$courseId': {
      id: '/_authenticated/university/$courseId'
      path: '/university/$courseId'
      fullPath: '/university/$courseId'
      preLoaderRoute: typeof AuthenticatedUniversityCourseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/reclaim-slots': {
      id: '/api/public/reclaim-slots'
      path: '/api/public/reclaim-slots'
      fullPath: '/api/public/reclaim-slots'
      preLoaderRoute: typeof ApiPublicReclaimSlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/university/': {
      id: '/_authenticated/admin/university/'
      path: '/university'
      fullPath: '/admin/university/'
      preLoaderRoute: typeof AuthenticatedAdminUniversityIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/university/$courseId': {
      id: '/_authenticated/admin/university/$courseId'
      path: '/university/$courseId'
      fullPath: '/admin/university/$courseId'
      preLoaderRoute: typeof AuthenticatedAdminUniversityCourseIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/business/analytics/': {
      id: '/_authenticated/business/analytics/'
      path: '/analytics'
      fullPath: '/business/analytics/'
      preLoaderRoute: typeof AuthenticatedBusinessAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedBusinessRouteRoute
    }
    '/_authenticated/business/analytics/$campaignId': {
      id: '/_authenticated/business/analytics/$campaignId'
      path: '/analytics/$campaignId'
      fullPath: '/business/analytics/$campaignId'
      preLoaderRoute: typeof AuthenticatedBusinessAnalyticsCampaignIdRouteImport
      parentRoute: typeof AuthenticatedBusinessRouteRoute
    }
    '/_authenticated/clipper/campaign/$campaignId': {
      id: '/_authenticated/clipper/campaign/$campaignId'
      path: '/campaign/$campaignId'
      fullPath: '/clipper/campaign/$campaignId'
      preLoaderRoute: typeof AuthenticatedClipperCampaignCampaignIdRouteImport
      parentRoute: typeof AuthenticatedClipperRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminBansRoute: typeof AuthenticatedAdminBansRoute
  AuthenticatedAdminClippersRoute: typeof AuthenticatedAdminClippersRoute
  AuthenticatedAdminEmailRoute: typeof AuthenticatedAdminEmailRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminPayoutsRoute: typeof AuthenticatedAdminPayoutsRoute
  AuthenticatedAdminScraperRoute: typeof AuthenticatedAdminScraperRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminViewsRoute: typeof AuthenticatedAdminViewsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminUniversityCourseIdRoute: typeof AuthenticatedAdminUniversityCourseIdRoute
  AuthenticatedAdminUniversityIndexRoute: typeof AuthenticatedAdminUniversityIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
    AuthenticatedAdminBansRoute: AuthenticatedAdminBansRoute,
    AuthenticatedAdminClippersRoute: AuthenticatedAdminClippersRoute,
    AuthenticatedAdminEmailRoute: AuthenticatedAdminEmailRoute,
    AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
    AuthenticatedAdminPayoutsRoute: AuthenticatedAdminPayoutsRoute,
    AuthenticatedAdminScraperRoute: AuthenticatedAdminScraperRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminViewsRoute: AuthenticatedAdminViewsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminUniversityCourseIdRoute:
      AuthenticatedAdminUniversityCourseIdRoute,
    AuthenticatedAdminUniversityIndexRoute:
      AuthenticatedAdminUniversityIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedBusinessRouteRouteChildren {
  AuthenticatedBusinessNewRoute: typeof AuthenticatedBusinessNewRoute
  AuthenticatedBusinessIndexRoute: typeof AuthenticatedBusinessIndexRoute
  AuthenticatedBusinessAnalyticsCampaignIdRoute: typeof AuthenticatedBusinessAnalyticsCampaignIdRoute
  AuthenticatedBusinessAnalyticsIndexRoute: typeof AuthenticatedBusinessAnalyticsIndexRoute
}

const AuthenticatedBusinessRouteRouteChildren: AuthenticatedBusinessRouteRouteChildren =
  {
    AuthenticatedBusinessNewRoute: AuthenticatedBusinessNewRoute,
    AuthenticatedBusinessIndexRoute: AuthenticatedBusinessIndexRoute,
    AuthenticatedBusinessAnalyticsCampaignIdRoute:
      AuthenticatedBusinessAnalyticsCampaignIdRoute,
    AuthenticatedBusinessAnalyticsIndexRoute:
      AuthenticatedBusinessAnalyticsIndexRoute,
  }

const AuthenticatedBusinessRouteRouteWithChildren =
  AuthenticatedBusinessRouteRoute._addFileChildren(
    AuthenticatedBusinessRouteRouteChildren,
  )

interface AuthenticatedClipperRouteRouteChildren {
  AuthenticatedClipperClipsRoute: typeof AuthenticatedClipperClipsRoute
  AuthenticatedClipperProfileRoute: typeof AuthenticatedClipperProfileRoute
  AuthenticatedClipperIndexRoute: typeof AuthenticatedClipperIndexRoute
  AuthenticatedClipperCampaignCampaignIdRoute: typeof AuthenticatedClipperCampaignCampaignIdRoute
}

const AuthenticatedClipperRouteRouteChildren: AuthenticatedClipperRouteRouteChildren =
  {
    AuthenticatedClipperClipsRoute: AuthenticatedClipperClipsRoute,
    AuthenticatedClipperProfileRoute: AuthenticatedClipperProfileRoute,
    AuthenticatedClipperIndexRoute: AuthenticatedClipperIndexRoute,
    AuthenticatedClipperCampaignCampaignIdRoute:
      AuthenticatedClipperCampaignCampaignIdRoute,
  }

const AuthenticatedClipperRouteRouteWithChildren =
  AuthenticatedClipperRouteRoute._addFileChildren(
    AuthenticatedClipperRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedBusinessRouteRoute: typeof AuthenticatedBusinessRouteRouteWithChildren
  AuthenticatedClipperRouteRoute: typeof AuthenticatedClipperRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedUniversityCourseIdRoute: typeof AuthenticatedUniversityCourseIdRoute
  AuthenticatedUniversityIndexRoute: typeof AuthenticatedUniversityIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedBusinessRouteRoute: AuthenticatedBusinessRouteRouteWithChildren,
  AuthenticatedClipperRouteRoute: AuthenticatedClipperRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedUniversityCourseIdRoute: AuthenticatedUniversityCourseIdRoute,
  AuthenticatedUniversityIndexRoute: AuthenticatedUniversityIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  BecomeAClipperRoute: BecomeAClipperRoute,
  ForBrandsRoute: ForBrandsRoute,
  ForClippersRoute: ForClippersRoute,
  ForCreatorsRoute: ForCreatorsRoute,
  LoginRoute: LoginRoute,
  PreviewRoute: PreviewRoute,
  SignupTypeRoute: SignupTypeRoute,
  ApiPublicReclaimSlotsRoute: ApiPublicReclaimSlotsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
